VEX_DIR=/home/ryan/tmp/ropc/bap-0.4/VEX
LIBASMIR_CXXFLAGS=-I/home/ryan/tmp/ropc/bap-0.4/VEX/pub -I/home/ryan/tmp/ropc/bap-0.4/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/ryan/tmp/ropc/bap-0.4/VEX -L/home/ryan/tmp/ropc/bap-0.4/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -ldl -liberty
